<? php
echo '<!DOCTYPE html>';
echo '<html lang="en" dir="ltr">';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '';
echo '<link rel="stylesheet" href="../My website/style login.css">';
echo '';
echo '<title>Login</title>';
echo '</head>';
echo '<body>';
echo '<form action="Login_action_page.php">';
echo '';
echo '';
echo '<div class="container">';
echo '<label for="username"><b>Username</b></label>';
echo '<input type="text" placeholder="Enter Username" name="username" required>';
echo '';
echo '<label for="password"><b>Password</b></label>';
echo '<input type="password" placeholder="Enter Password" name="password" required>';
echo '';
echo '<button type="submit">Login</button>';
echo '';
echo '<label>';
echo '<input type="checkbox" checked="checked" name="remember"> Remember me';
echo '</label>';
echo '</div>';
echo '';
echo '<div class="container" style="background-color:#f1f1f1">';
echo '<button type="button" class="cancelbtn"><a href="../My website/Mywebsite.html">Cancel</a></button>';
echo '<button type="button" class="signupbtn"><a href="../My website/Sign%20up.php">Sign up</a></button>';
echo '<span class="password">Forgot<a href="#" class="link">password?</a></span>';
echo '</div>';
echo '</form>';
echo '</body>';
echo '</html>';
echo '';
?>
