<? php
echo '<!DOCTYPE html>';
echo '<html lang="en" dir="ltr">';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '';
echo '<link rel="stylesheet" href="../My website/Mainshoppingsite.css">';
echo '';
echo '';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">';
echo '';
echo '';
echo '<title>Main website</title>';
echo '</head>';
echo '<body>';
echo '<!-- The navigation menu -->';
echo '<div class="navbar">';
echo '<a href="../My website/Mywebsite.html">Home</a>';
echo '<div class="subnav">';
echo '<button class="subnavbtn">Categories<i class="fa fa-caret-down"></i></button>';
echo '<div class="subnav-content">';
echo '<a href="../My website/Mainshoppingsite.php?CategoryID=<?=10000?>">Sneaker</a>';
echo '<a href="../My website/Mainshoppingsite.php?CategoryID=<?=20000?>">Leather</a>';
echo '<a href="../My website/Mainshoppingsite.php?CategoryID=<?=30000?>">Lifestyle</a>';
echo '</div>';
echo '</div>';
echo '<div class="subnav">';
echo '<button class="subnavbtn">Product<i class="fa fa-caret-down"></i></button>';
echo '<div class="subnav-content">';
echo '<a href="../My website/Add.php">Add</a>';
echo '<a href="../My website/Update.php">Update</a>';
echo '<a href="../My website/Delete.php">Delete</a>';
echo '</div>';
echo '</div>';
echo '<div class="subnav">';
echo '<button class="subnavbtn">Partners <i class="fa fa-caret-down"></i></button>';
echo '<div class="subnav-content">';
echo '<a href="../My website/Mainshoppingsite.php?PartnerID=<?=1000?>">Adidas</a>';
echo '<a href="../My website/Mainshoppingsite.php?PartnerID=<?=1001?>">Calvin Klein</a>';
echo '<a href="../My website/Mainshoppingsite.php?PartnerID=<?=1002?>">LA Gear</a>';
echo '<a href="../My website/Mainshoppingsite.php?PartnerID=<?=1003?>">Crocs</a>';
echo '</div>';
echo '</div>';
echo '<a href="../My website/Shoppingcart.php">Go to cart</a>';
echo '<form class="search" action="../My website/Mainshoppingsite.php" method="GET" >';
echo '<div class="search">';
echo '<input type="text" name="search" placeholder="Search..">';
echo '<button type="submit"><i class="fa fa-search"></i></button>';
echo '</div>';
echo '</form>';
echo '';
echo '';
echo '</div>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '<!showproduct>';
echo '<div class="showproduct">';
echo '<div class="row">';
echo '<?php';
echo 'require_once './Function.php';';
echo 'if (isset($_GET['CategoryID'])) {';
echo '$categoryID=$_GET['CategoryID'];';
echo '$sql="select*from product where CategoryID='$categoryID' ";';
echo '';
echo '';
echo '}';
echo '';
echo 'else if (isset($_GET['PartnerID'])) {';
echo '$partnersID=$_GET['PartnerID'];';
echo '$sql="select*from product where PartnerID='$partnersID' ";';
echo '}';
echo '';
echo 'else if (isset($_GET['ProductPrice']))';
echo '{';
echo '$productprice=$_GET['ProductPrice'];';
echo '$sql="select*from product where ProductPrice='$productprice' ";';
echo '';
echo '}';
echo '';
echo 'else if (isset($_GET['search'])) {';
echo '$search=$_GET['search'];';
echo '$sql="select * from product where ProductName like '%$search%'";';
echo '';
echo '}';
echo 'else {';
echo '';
echo '$sql="select*from product";';
echo '}';
echo '';
echo '$Producttable=query($sql);';
echo 'for($i=0;$i<count($Producttable);$i++){';
echo '?>';
echo '<div class="column">';
echo '<img src="<?=$Producttable[$i][3] ?>" alt="img" style="width:100%">';
echo '<div class="overlay">';
echo '<a href="../My website/Showproduct.php?ProductID=<?=$Producttable[$i][0]?>"><p class="overlay-text"><?=$Producttable[$i][1]?></p></a>';
echo '';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<?php';
echo '}';
echo '?>';
echo '</div>';
echo '</div>';
echo '</body>';
echo '</html>';
echo '';
?>
