<? php
echo '';
echo '<link rel="stylesheet" href="../My website/showproduct.css">';
echo '<title>Show product</title>';
echo '<div class="topnav">';
echo '<a class="active" href="../My website/Mywebsite.html">Home</a>';
echo '<a href="../My website/Shoppingcart.php">Go to cart</a>';
echo '<a href="../My website/Mainshoppingsite.php">Main site</a>';
echo '';
echo '';
echo '</div>';
echo '';
echo '<?php';
echo '';
echo '';
echo 'require_once './Function.php';';
echo '$productID=$_GET['ProductID'];';
echo '$sql="select * from product where ProductID=$productID";';
echo '$producttable=query($sql);';
echo '';
echo '?>';
echo '<body>';
echo '';
echo '';
echo '<div class="showproduct">';
echo '<div class="productimg">';
echo '<img src="<?=$producttable[0][3]?>" alt="Product Img">';
echo '</div>';
echo '';
echo '<div class="productdescription">';
echo '<p class="productname"><?=$producttable[0][1]?></p>';
echo '<p class="productprice"><?="Price:$".$producttable[0][2]?></p>';
echo '<p>Description :</p>';
echo '<p class="productdesc"><?=$producttable[0][5]?></p>';
echo '';
echo '</div>';
echo '';
echo '<a href="../My website/Shoppingcart.php"> <button type="button" name="button">Go to cart</button></a>';
echo '';
echo '</body>';
echo '';
echo '';
echo '</div>';
echo '';
?>
