<? php
echo '<!DOCTYPE html>';
echo '<html lang="en" dir="ltr">';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<link rel="stylesheet" href="../My website/style signup.css">';
echo '<title>Sign up</title>';
echo '</head>';
echo '<body>';
echo '<form action="Sign_up_action_page.php" method="get" style="border:1px solid #ccc">';
echo '<div class="container">';
echo '<h1>Sign Up</h1>';
echo '<p>Please fill in this form to create an account.</p>';
echo '<hr>';
echo '';
echo '<label for="Username1"><b>Username</b></label>';
echo '<input type="text" placeholder="Enter Username" name="Username1"required>';
echo '';
echo '<label for="Password1"><b>Password</b></label>';
echo '<input type="password" placeholder="Enter Password" name="Password1" required>';
echo '';
echo '<label for="Password-repeat1"><b>Repeat Password</b></label>';
echo '<input type="password" placeholder="Repeat Password" name="Password-repeat1" required>';
echo '';
echo '';
echo '<p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>';
echo '';
echo '<div class="clearfix">';
echo '<button type="button" class="cancelbtn"><a href="../My website/Mywebsite.html">Cancel</a></button>';
echo '<button type="submit" class="signupbtn">Sign Up</button>';
echo '</div>';
echo '</div>';
echo '</form>';
echo '</body>';
echo '</html>';
echo '';
?>
